### ISSUE TITLE
Webhook sensio

### ISSUE THREAD

**Issue by viviengaetan** [projet-normandie/BadgeBundle#6]
Nico, je vois que tu as mis un hook sur sensio, est-ce que tu veux que l'on en laisse qu'un seul ?

2 c'est autant de fois plus d'appels chez eux et deux fois plus de temps pour nous...

**Comment by niconoe-** [comment]
Oui bien sur, on laisse le tiens.
J'ai fait plusieurs tests de mon côté ce qui impliquait d'avoir besoin de hooker de mon côté, vu que je n'avais pas tes accès.

**Comment by niconoe-** [comment]
Seul ton webhook sensio a été conservé en mode pull_request && push.
Résolu.

**Comment by viviengaetan** [comment]
Alors il faudrait peut-être que l'on voit si on peut rendre ça accessible à tous non ?
